language: ruby
before_script:
  - psql -c 'create database bike_bin_test;' -U postgres
rvm:
  - 2.5.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake test
  # - bundle exec rake test:system